from __future__ import annotations

from typing import Any


class Operations:
	def create_table(self, *args: Any, **kwargs: Any) -> Any: ...
	def drop_table(self, *args: Any, **kwargs: Any) -> Any: ...
	def create_index(self, *args: Any, **kwargs: Any) -> Any: ...
	def drop_index(self, *args: Any, **kwargs: Any) -> Any: ...
	def create_foreign_key(self, *args: Any, **kwargs: Any) -> Any: ...
	def drop_constraint(self, *args: Any, **kwargs: Any) -> Any: ...


op: Operations


