[general]
# Дополнительные глобальные инструкции для всех действий PR-Agent
extra_instructions = "Пожалуйста, веди весь диалог и комментарии на русском языке. Пиши кратко, по делу, с конкретными рекомендациями."

[pr_reviewer]
# Короткие, практичные комментарии; без избыточной болтовни
review_depth = "standard"
extra_instructions = "Формулируй замечания и предложения на русском языке. Отмечай важность: [Критично], [Важно], [Нитпик]. Если есть быстрая правка — предложи её."

[pr_description]
extra_instructions = "Генерируй/улучшай описание PR на русском языке, добавляй краткий список изменений и риски, если есть."

[pr_questions]
extra_instructions = "Отвечай на вопросы по PR на русском языке."

[pr_commands]
extra_instructions = "Все ответы — на русском языке."

