name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e services/tg_bot -e services/http_service 'pytest>=8.0' pytest-asyncio pytest-faker faker respx
      - name: Run tests
        env:
          TG_BOT_DATABASE_URL: postgresql+psycopg://postgres:postgres@127.0.0.1:5432/tg_bot_ci
        run: |
          PYTHONPATH=services/tg_bot/src:services/http_service/src pytest -q


